from enum import Enum


class DrivingConfig(Enum):

    # commands config
    COMMAND_ACTIVITY_ARG = 'activity'

    # servo
    SERVO_CONFIG = 'SERVO_CONFIG'
    SERVO_PIN_NUMBER = 'SERVO_PIN_NUMBER'
    SERVO_BOARD_MODE = 'SERVO_BOARD_MODE'
    SERVO_VOLTAGE_OUTPUT_LEVEL = 'SERVO_VOLTAGE_OUTPUT_LEVEL'

    # motor
    # todo
    MOTOR_CONFIG = 'MOTOR_CONFIG'
    MOTOR_PIN_NUMBER_IN1 = 'MOTOR_PIN_NUMBER_IN1'
    MOTOR_PIN_NUMBER_IN2 = 'MOTOR_PIN_NUMBER_IN2'
    MOTOR_PIN_NUMBER_PWM = 'MOTOR_PIN_NUMBER_PWM'
    MOTOR_PIN_NUMBER_SBY = 'MOTOR_PIN_NUMBER_SBY'
    MOTOR_PIN_DIRECTION = 'MOTOR_PIN_DIRECTION'
    MOTOR_BOARD_MODE = 'MOTOR_BOARD_MODE'

    # obstacle sensor
    OBSTACLE_SENSOR_USING_SENSOR = 'OBSTACLE_SENSOR_USING_SENSOR'
    OBSTACLE_SENSOR_PIN_NUMBER = 'OBSTACLE_SENSOR_PIN_NUMBER'
    OBSTACLE_SENSOR_BOARD_MODE = 'OBSTACLE_SENSOR_BOARD_MODE'
    OBSTACLE_SENSOR_WITH_CALLBACK = 'OBSTACLE_SENSOR_WITH_CALLBACK'
    OBSTACLE_SENSOR_BOUNCETIME = 'OBSTACLE_SENSOR_BOUNCETIME'
    # dict value list indices!
    OBSTACLE_FRONT_SENSOR = 'OBSTACLE_FRONT_SENSOR'
    OBSTACLE_BACK_SENSOR = 'OBSTACLE_BACK_SENSOR'

    # LEDs
    LED_PIN_NUMBER = 'LED_PIN_NUMBER'
    LED_PIN_DIRECTION = 'LED_PIN_DIRECTION'
    LED_BOARD_MODE = 'LED_BOARD_MODE'
    # LEDs from front & back side of car!
    LEDs_FRONT = 'LEDs_FRONT'
    LEDs_BACK = 'LEDs_BACK'
    # LED id from front & back list!
    LEDs_FRONT_LEFT = 'LEDs_FRONT_LEFT'
    LEDs_FRONT_RIGHT = 'LEDs_FRONT_RIGHT'
    LEDs_BACK_LEFT = 'LEDs_BACK_LEFT'
    LEDs_BACK_RIGHT = 'LEDs_BACK_RIGHT'
