from enum import Enum


class InputConfig(Enum):

    ACTIVITY_TYPE_FIELD = 'ACTIVITY_TYPE_FIELD'

# driving activity
    DRIVING_COMMANDS = 'DRIVING_COMMANDS'
    DRIVING_DIRECTION_TYPE = 'DRIVING_DIRECTION_TYPE'
    # forward & backward & none
    DRIVING_WHEEL_TURN = 'DRIVING_WHEEL_TURN'
    DRIVING_EXECUTION_TIME = 'DRIVING_EXECUTION_TIME'
    DRIVING_EXECUTION_TIME_FORMAT = '%H:%M:%S'

    DRIVING_USE_SENSORS_FIELD = 'DRIVING_USE_SENSORS_FIELD'
    DRIVING_USE_LEDs_FIELD = 'DRIVING_USE_LEDs_FIELD'
